name: Build Hash Database

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Create DB
        run: go run db_generator.go
        env:
          GOWORK: off
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: "ROMnibus.sqlite"
          path: "ROMnibus.sqlite"
          if-no-files-found: error
          retention-days: 7
          overwrite: true