name: Build Hash Database

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Create DB
        run: go run db_generator.go
        env:
          GOWORK: off
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Release and Upload Asset
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Create release if it doesn't exist
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated release for ${{ github.ref_name }}" \
            --draft=false \
            --prerelease=false \
            || true  # Don't fail if release already exists

          # Upload the database file
          gh release upload ${{ github.ref_name }} ROMnibus.sqlite --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
