name: Build Hash Database

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Create DB
        run: go run db_generator.go
        env:
          GOWORK: off
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create Release and Upload Asset
        run: |
          TAG="release-$(date +%Y%m%d-%H%M%S)"

          gh release create $TAG \
            --title "Database Release $TAG" \
            --notes "Automated database release generated on $(date)" \
            --draft=false \
            --prerelease=false

          gh release upload $TAG ROMnibus.sqlite --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

